param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [ValidateRange(4, 256)]
    [int]$ReplicaCount = 4,
    [ValidateSet("Normal", "Fault")]
    [string]$RunMode = "Normal",
    [ValidateRange(0, 255)]
    [int]$DownReplicaCount = 0,
    [ValidateRange(1, 32)]
    [int]$ClientCount = 1,
    [int]$BaseClientPort = 11000,
    [int]$PortStep = 10,
    [switch]$LaunchReplicas,
    [ValidateSet("Normal", "Minimized", "Maximized")]
    [string]$ReplicaWindowStyle = "Normal",
    [ValidateRange(5, 300)]
    [int]$ReadyTimeoutSec = 90
)

$ErrorActionPreference = "Stop"

$gradleUserHome = Join-Path $RepoRoot ".gradle-home"
$gradlew = Join-Path $RepoRoot "gradlew.bat"
$installRoot = Join-Path $RepoRoot "build\install\library"
$localRoot = Join-Path $RepoRoot "build\local"
$rootConfigDir = Join-Path $RepoRoot "config"
$templateSystemConfig = Join-Path $rootConfigDir "system.config"

function Get-ReplicaIds {
    param([int]$Count)
    return 0..($Count - 1)
}

function Get-PlannedDownReplicaIds {
    param(
        [int]$Count,
        [int]$DownCount
    )

    if ($DownCount -le 0) {
        return @()
    }

    $start = $Count - $DownCount
    return $start..($Count - 1)
}

function Get-ReplicaClientPort {
    param(
        [int]$ReplicaId,
        [int]$StartPort,
        [int]$Increment
    )

    return $StartPort + ($ReplicaId * $Increment)
}

function New-HostsConfigText {
    param(
        [int]$Count,
        [int]$StartPort,
        [int]$Increment
    )

    $lines = @(
        "# Auto-generated by runscripts/start-simple-incident-demo.ps1",
        "# server id, address, client port, replica port"
    )

    foreach ($id in (Get-ReplicaIds -Count $Count)) {
        $clientPort = $StartPort + ($id * $Increment)
        $serverPort = $clientPort + 1
        $lines += ("{0} 127.0.0.1 {1} {2}" -f $id, $clientPort, $serverPort)
    }

    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function New-SystemConfigText {
    param(
        [string]$TemplatePath,
        [int]$Count
    )

    $f = [math]::Floor(($Count - 1) / 3)
    $initialView = ((Get-ReplicaIds -Count $Count) -join ",")
    $text = Get-Content -Path $TemplatePath -Raw
    $text = $text -replace '(?m)^system\.servers\.num\s*=.*$', ("system.servers.num = {0}" -f $Count)
    $text = $text -replace '(?m)^system\.servers\.f\s*=.*$', ("system.servers.f = {0}" -f $f)
    $text = $text -replace '(?m)^system\.initial\.view\s*=.*$', ("system.initial.view = {0}" -f $initialView)
    return $text
}

function Copy-InstallTree {
    param(
        [string]$SourceDirectory,
        [string]$DestinationDirectory
    )

    New-Item -ItemType Directory -Force -Path $DestinationDirectory | Out-Null
    Copy-Item -Path (Join-Path $SourceDirectory '*') -Destination $DestinationDirectory -Recurse -Force
}

function Write-ReplicaConfig {
    param(
        [string]$TargetDirectory,
        [string]$HostsConfigText,
        [string]$SystemConfigText
    )

    $configDir = Join-Path $TargetDirectory "config"
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
    Set-Content -Path (Join-Path $configDir "hosts.config") -Value $HostsConfigText -NoNewline
    Set-Content -Path (Join-Path $configDir "system.config") -Value $SystemConfigText -NoNewline

    $currentView = Join-Path $configDir "currentView"
    if (Test-Path $currentView) {
        Remove-Item -LiteralPath $currentView -Force
    }
}

function Test-PortListening {
    param([int]$Port)

    $match = netstat -ano | Select-String (":{0}\s" -f $Port) | Select-Object -First 1
    return $null -ne $match
}

function Wait-ForReplicaReady {
    param(
        [int[]]$ReplicaIds,
        [int]$ExpectedReadyCount,
        [int]$StartPort,
        [int]$Increment,
        [int]$TimeoutSec
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    do {
        $readyIds = @()
        foreach ($id in $ReplicaIds) {
            $clientPort = Get-ReplicaClientPort -ReplicaId $id -StartPort $StartPort -Increment $Increment
            if (Test-PortListening -Port $clientPort) {
                $readyIds += $id
            }
        }

        Write-Host ("  ready replicas: {0}/{1} -> [{2}]" -f $readyIds.Count, $ExpectedReadyCount, ($readyIds -join ", "))
        if ($readyIds.Count -ge $ExpectedReadyCount) {
            return $true
        }

        Start-Sleep -Seconds 2
    } while ((Get-Date) -lt $deadline)

    return $false
}

function Start-ReplicaWindows {
    param(
        [string]$LocalDirectory,
        [int]$Count,
        [string]$WindowStyle
    )

    foreach ($id in (Get-ReplicaIds -Count $Count)) {
        $target = Join-Path $LocalDirectory ("rep{0}" -f $id)
        $title = "simple-pbft-rep{0}" -f $id
        $command = "Set-Location '{0}'; `$Host.UI.RawUI.WindowTitle = '{1}'; cmd /c smartrun.cmd bftsmart.demo.incidentsimple.SimpleIncidentServer {2}" -f $target, $title, $id
        $process = Start-Process -FilePath "powershell.exe" `
            -WorkingDirectory $target `
            -ArgumentList @("-NoExit", "-ExecutionPolicy", "Bypass", "-Command", $command) `
            -WindowStyle $WindowStyle `
            -PassThru

        Set-Content -Path (Join-Path $target "replica.pid") -Value $process.Id
        Write-Host ("  launched rep{0} in a new PowerShell window (PID {1})" -f $id, $process.Id)
    }
}

if ($RunMode -eq "Fault" -and $DownReplicaCount -le 0) {
    throw "Fault mode requires -DownReplicaCount to be at least 1."
}

if ($DownReplicaCount -ge $ReplicaCount) {
    throw "DownReplicaCount must be smaller than ReplicaCount."
}

$f = [math]::Floor(($ReplicaCount - 1) / 3)
$demoThreshold = [math]::Min(2, [math]::Max(1, $ReplicaCount - 1))
$allWitnessThreshold = [math]::Max(1, $ReplicaCount - 1)
$plannedDownReplicaIds = @(Get-PlannedDownReplicaIds -Count $ReplicaCount -DownCount $DownReplicaCount)
$activeReplicaIds = @(Get-ReplicaIds -Count $ReplicaCount | Where-Object { $plannedDownReplicaIds -notcontains $_ })
$expectedReadyCount = $activeReplicaIds.Count

Write-Host "Building distribution into build/install/library ..."
$env:GRADLE_USER_HOME = $gradleUserHome
& $gradlew installDist | Out-Host
if ($LASTEXITCODE -ne 0) {
    throw "Gradle installDist failed with exit code $LASTEXITCODE."
}

New-Item -ItemType Directory -Force -Path $localRoot | Out-Null
Get-ChildItem -Path $localRoot -Directory -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match '^(rep|cli)\d+$' } |
    Remove-Item -Recurse -Force

$hostsConfigText = New-HostsConfigText -Count $ReplicaCount -StartPort $BaseClientPort -Increment $PortStep
$systemConfigText = New-SystemConfigText -TemplatePath $templateSystemConfig -Count $ReplicaCount

foreach ($id in (Get-ReplicaIds -Count $ReplicaCount)) {
    $target = Join-Path $localRoot ("rep{0}" -f $id)
    Copy-InstallTree -SourceDirectory $installRoot -DestinationDirectory $target
    Write-ReplicaConfig -TargetDirectory $target -HostsConfigText $hostsConfigText -SystemConfigText $systemConfigText
}

foreach ($id in 0..($ClientCount - 1)) {
    $target = Join-Path $localRoot ("cli{0}" -f $id)
    Copy-InstallTree -SourceDirectory $installRoot -DestinationDirectory $target
    Write-ReplicaConfig -TargetDirectory $target -HostsConfigText $hostsConfigText -SystemConfigText $systemConfigText
}

Write-Host ""
Write-Host ("Replica count: {0} (computed f = {1})" -f $ReplicaCount, $f)
Write-Host ("Run mode: {0}" -f $RunMode)
if ($RunMode -eq "Fault") {
    Write-Host ("Planned down replicas (highest ids): [{0}]" -f ($plannedDownReplicaIds -join ", "))
    Write-Host ("Expected ready replicas after faults: {0}" -f $expectedReadyCount)
}

if ($LaunchReplicas) {
    Write-Host ("Launching {0} replica windows..." -f $ReplicaCount)
    Start-ReplicaWindows -LocalDirectory $localRoot -Count $ReplicaCount -WindowStyle $ReplicaWindowStyle

    Write-Host ("Waiting for {0} replica(s) to listen on their client ports..." -f $expectedReadyCount)
    if (Wait-ForReplicaReady -ReplicaIds $activeReplicaIds -ExpectedReadyCount $expectedReadyCount -StartPort $BaseClientPort -Increment $PortStep -TimeoutSec $ReadyTimeoutSec) {
        Write-Host "Replica readiness target reached."
        if ($RunMode -eq "Fault") {
            Write-Host ("For the fault run, stop these replica windows with Ctrl+C then Y: rep{0}" -f ($plannedDownReplicaIds -join ", rep"))
        }
    } else {
        Write-Warning ("Timed out waiting for {0} ready replica(s)." -f $expectedReadyCount)
    }
} else {
    Write-Host "Start the simple PBFT incident replicas in separate terminals:"
    foreach ($id in (Get-ReplicaIds -Count $ReplicaCount)) {
        Write-Host ("  Set-Location `"{0}`"; cmd /c smartrun.cmd bftsmart.demo.incidentsimple.SimpleIncidentServer {1}" -f (Join-Path $localRoot ("rep{0}" -f $id)), $id)
    }
}

Write-Host ""
Write-Host ("Demo scenario using threshold {0}:" -f $demoThreshold)
Write-Host ("  Set-Location `"{0}`"; cmd /c smartrun.cmd bftsmart.demo.incidentsimple.SimpleIncidentClient 1001 submit-incident incident-001 ship-A {1} Collision reported near waypoint 17" -f (Join-Path $localRoot "cli0"), $demoThreshold)
Write-Host ("  Set-Location `"{0}`"; cmd /c smartrun.cmd bftsmart.demo.incidentsimple.SimpleIncidentClient 1002 confirm-incident incident-001 ship-B" -f (Join-Path $localRoot "cli0"))
Write-Host ("  Set-Location `"{0}`"; cmd /c smartrun.cmd bftsmart.demo.incidentsimple.SimpleIncidentClient 1003 confirm-incident incident-001 ship-C" -f (Join-Path $localRoot "cli0"))
Write-Host ("  Set-Location `"{0}`"; cmd /c smartrun.cmd bftsmart.demo.incidentsimple.SimpleIncidentClient 1004 get-incident incident-001" -f (Join-Path $localRoot "cli0"))

Write-Host ""
Write-Host ("If you want every other ship to confirm in a {0}-replica run, use threshold {1} on submit." -f $ReplicaCount, $allWitnessThreshold)

Write-Host ""
Write-Host "Useful options:"
Write-Host "  -LaunchReplicas                 Automatically open one PowerShell window per replica"
Write-Host "  -ReplicaWindowStyle Minimized  Useful when starting many replicas (10, 20, ...)"
Write-Host "  -RunMode Fault -DownReplicaCount 3"
Write-Host "                                 Treat the highest replica ids as the planned down nodes"

Write-Host ""
Write-Host "To stop replicas created for the current simple demo setup:"
Write-Host ("  powershell -ExecutionPolicy Bypass -File `"{0}`"" -f (Join-Path $PSScriptRoot "stop-simple-incident-demo.ps1"))
Write-Host "  (This now removes build\\local\\rep* and cli* copies by default. Use -KeepLocalCopies to keep them.)"
